module.exports = {
    changeReasonController: require('./changeReasonController'),
    changeTypeController: require('./changeTypeController'),
    impactController: require('./impactController'),
    investigationReasonController: require('./investigationReasonController'),
    issueTypeController: require('./issueTypeController'),
    priorityController: require('./priorityController'),
    requestTypeController: require('./requestTypeController'),
    statusController: require('./statusController'),
    statusTypeController: require('./statusTypeController'),
    ticketCommentController: require('./ticketCommentController'),
    ticketController: require('./ticketController'),
    ticketFileController: require('./ticketFileController'),
    ticketHistoryController: require('./ticketHistoryController'),
}