'use strict'
module.exports = {
    Product: require('./product'),
    ProductAuditLog: require('./productAuditLog'),
    ProductCategory: require('./productCategory'),
    ProductLicense: require('./productLicense'),
    ProductModel: require('./productModel'),
    ProductNote: require('./productNote'),
    ProductStatus: require('./productStatus'),
    ProductSupplier: require('./productSupplier'),
    ProductTechParam: require('./productTechParam'),
    ProductTechParamCategory: require('./productTechParamCategory'),
    ProductTechParamValue: require('./productTechParamValue'),
    ProductTool: require('./productTool'),
    ProductToolInstalled: require('./productToolInstalled'),
    ProductConnection: require('./productConnection'),
    ProductDrawing: require('./productDrawing'),
    ProductCheckItem: require('./productCheckItem'),
    ProductServiceReportTemplate: require('./productServiceReportTemplate'),
    ProductServiceReports: require('./productServiceReports'),
    ProductServiceReportFiles: require('./productServiceReportFile'),
    ProductCheckItemCategory: require('./productCheckItemCategory'),
    ProductProfile: require('./productProfile'),
    ProductServiceReportValue: require('./productServiceReportValue'),
    ProductServiceReportValueFile: require('./productServiceReportValueFile'),
    CategoryGroup: require('./categoryGroup'),
}