module.exports = {
    productAuditLogController: require('./productAuditLogController'),
    productCategoryController: require('./productCategoryController'),
    productConnectionController: require('./productConnectionController'),
    productController: require('./productController'),
    productDrawingController: require('./productDrawingController'),
    productLicenseController: require('./productLicenseController'),
    productModelController: require('./productModelController'),
    productNoteController: require('./productNoteController'),
    productStatusController: require('./productStatusController'),
    productSupplierController: require('./productSupplierController'),
    productTechParamCategoryController: require('./productTechParamCategoryController'),
    productTechParamController: require('./productTechParamController'),
    productTechParamValueController: require('./productTechParamValueController'),
    productToolController: require('./productToolController'),
    productToolInstalledController: require('./productToolInstalledController'),
    productCheckItemsController: require('./productCheckItemsController'),
    productServiceReportTemplateController: require('./productServiceReportTemplateController'),
    productServiceReportController: require('./productServiceReportController'),
    productServiceReportFileController: require('./productServiceReportFileController'),
    productCheckItemCategoryController: require('./productCheckItemCategoryController'),
    productProfileController: require('./productProfileController'),
    productServiceReportValueController: require('./productServiceReportValueController'),
    productServiceReportValueFileController: require('./productServiceReportValueFileController'),
    categoryGroupController: require('./categoryGroupController'),
    productIntegrationController: require('./productIntegrationController'),
}