module.exports = {
    securityRoleController: require('./securityRoleController'),
    securityModuleController: require('./securityModuleController'),
    securityConfigController: require('./securityConfigController'),
    securityAuthenticationController: require('./securityAuthenticationController'),
    customerAuthenticationController: require('./customerAuthenticationController'),
    securityUserController: require('./securityUserController'),
    securityAudiLogController: require('./securityAuditLogController'),
    securitySignInLogController: require('./securitySignInLogController'),
    securityNoteController: require('./securityNoteController'),
    securityUserInvitationController: require('./securityUserInvitationController'),
    securityConfigBlockedUserController: require('./securityConfigBlockedUserController'),
    securityConfigBlockedCustomerController: require('./securityConfigBlockedCustomerController'),
    securityConfigWhileListIPController: require('./securityConfigWhiteListIPController'),
    securityConfigBlackListIPController: require('./securityConfigBlackListIPController'),
    securityNotificationController: require('./securityNotificationController'),
}